### ISSUE TITLE
Running into this issue when I run either the CLI app or import it into my code :)

### ISSUE THREAD

**Issue by GarnetSunset** [snipem/psnprices#12]
```Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\James\PycharmProjects\psDLCIndex\venv\Scripts\psncli.exe\__main__.py", line 4, in <module>
  File "c:\users\james\pycharmprojects\psdlcindex\venv\lib\site-packages\gameprices\__init__.py", line 1, in <module>
    from .shops import psn
  File "c:\users\james\pycharmprojects\psdlcindex\venv\lib\site-packages\gameprices\shops\psn.py", line 6, in <module>
    from gameprices.offer import GameOffer, Price
  File "c:\users\james\pycharmprojects\psdlcindex\venv\lib\site-packages\gameprices\offer.py", line 6, in <module>
    class GameOffer(object):
  File "c:\users\james\pycharmprojects\psdlcindex\venv\lib\site-packages\gameprices\offer.py", line 10, in GameOffer
    prices: list[Price] = []
TypeError: 'type' object is not subscriptable
```

**Comment by snipem** [comment]
What is the command you are using?

**Comment by snipem** [comment]
What do you do with the imports? I want to write a test for it and reproduce it. If I run 

```bash
> python3                          
Python 3.9.10 (main, Jan 15 2022, 17:48:00) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gameprices.shops import psn
>>> from gameprices.shops.psn import Psn
>>> p = psn.Psn(country="DE/de")
>>> p.search("Metal Gear")
>>> ....

```
Everything works.

**Comment by GarnetSunset** [comment]
Yep I agree, no clue what happened.
